name: Build Bindings

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Linux:
    uses: ./.github/workflows/build-job.yml
    with:
      name: Linux
      runner_generate: ubuntu-22.04
      runner_compile: ubuntu-22.04
      platform: Linux
    secrets:
      ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

